// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfybkjbqovrqzoleddeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmeWJramJxb3ZycXpvbGVkZGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDk0ODgsImV4cCI6MjA2Njg4NTQ4OH0.faIguKFKTVipe9m7lCQESGcITzT5YJ1x6TrQ_4kvBV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});